### PR TITLE
Add reset method

### PR DESCRIPTION
**Pull request by danny-andrews**
Refs #56.

### CODE REVIEW

**Comment by vvo** [comment]
Hi, can you fix the failing build (linting). thanks

**Comment by danny-andrews** [comment]
Done!

**Comment by vvo** [comment]
LGTM

**Comment by vvo** [comment]
Can you add some documentation on it?

**Comment by danny-andrews** [comment]
https://github.com/mjackson/expect/pull/65

**Comment by mjackson** [comment]
Thanks, @danny-andrews and @vvo! :D

**Pull request merged**
