### PR TITLE
add satisfy method to expectation class

### PR DESCRIPTION
**Pull request by lvfx93**
I added a method for 'generic tests' called satisfy(alias: meet), hope it helps if the existing methods don't 'meet' what the test needs.

### CODE REVIEW

**Comment by lvfx93** [comment]
I had a problem running the command "npm run lint". I guess that I'm running it on Windows 10.

**Comment by lvfx93** [comment]
I stuck trying to discover why Travis build failed at Firefox 43 and Chrome 47 on Windows 10, Safari 9 in Mac OSX. Maybe a assert npm module problem or the use of arrow functions on tests?

**Comment by ljharb** [comment]
Is this a pattern from other test frameworks? I'm curious why you wouldn't just use `expect(callback(obj)).to.equal(true, msg)`

**Comment by lvfx93** [comment]
@ljharb, thanks for the heads up, I didn't even know this existed, sorry.

**Comment by lvfx93** [comment]
@ljharb, please, if possible add it to the docs. Maybe other people are looking for this, too.

**Pull request closed without merging**
