### PR TITLE
use Rollup for bundling

### PR DESCRIPTION
**Pull request by Rich-Harris**
[Couldn't help myself...](https://twitter.com/mjackson/status/765305385364226049)

Results:

``` bash
$ time npm run build
# ...
gzipped, the UMD build is 8.4 kB
expect.js took 7ms to initialise
expect.min.js took 7ms to initialise
npm run build  3.59s user 0.33s system 110% cpu 3.561 total

$ git checkout master
$ time npm run build
# ...
gzipped, the UMD build is 15.44 kB
expect.js took 19ms to initialise
expect.min.js took 15ms to initialise
npm run build  5.69s user 0.50s system 111% cpu 5.522 total
```

Note: the Rollup config uses [rollup-plugin-buble](https://gitlab.com/Rich-Harris/rollup-plugin-buble) rather than [rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel). I made a good faith attempt to get it to work with Babel but I got stuck trying to configure presets etc and gave up.

**There are two failing tests** – the ones related to default exports. Basically, Rollup has a couple of export modes – `default` (equates to `module.exports = ...`) or `named` (equates to `exports.foo = ...`. If there are named exports, it uses `named` mode, which entails adding the default export as `exports['default']`, which means CommonJS consumers have to do `require('expect').default` – obviously not ideal.

I usually recommend that people either use a single default export or only use named exports, as it gets around this interop headache. That's an option here (`export default expect`, with all the additional exports as properties of that function), though it feels a bit grubby and I think some tests would need to change. Not sure what the ideal solution is.

### CODE REVIEW

**Comment by mjackson** [comment]
Thank you @Rich-Harris! This looks great.

I've been reading through the Rollup config this morning, just trying to understand how it all works. Learning a new build tool always takes a bit of time ;) I'll have some more concrete feedback this afternoon.

**Comment by Rich-Harris** [comment]
Take your time – and if you get stuck let me know because it probably means our documentation needs to get better!

I was thinking about the best way to smooth over the interop headaches – I wondered if you'd considered bundling the CJS files as well? So you'd have one UMD bundle that includes dependencies, for browsers, and a separate CJS bundle that *didn't* include dependencies. That way you'd have a completely consistent interface (presumably with just the default export, to avoid the `require(...).default` nonsense). Only downside would be if consumers of the library wanted to import modules individually (i.e. `import { createSpy } from 'expect/lib/SpyUtils.js'`) – I don't know if that's a factor here?

But I'm just spitballing, you do you!

**Comment by robcolburn** [comment]
Travis says that tests are failing because Karma is still wired to Webpack. Did you intend to change that / forget to push that change?

**Comment by Rich-Harris** [comment]
@robcolburn ah, whoops! Rookie mistake, I'm not familiar with Karma, just assumed it would use `npm run build`. Can you give me any pointers on how to rig it up? Thanks

**Comment by hzoo** [comment]
Not that I'm suggesting this needs to change to use Babel but just as FYI @Rich-Harris the config can be

```js
{
  "presets": [
    ["es2015", { "modules": false }]
  ]
}
```

Nice that the readme has this too now! https://github.com/rollup/rollup-plugin-babel#configuring-babel

**Comment by mjackson** [comment]
Hi @hzoo, thanks for chiming in here. I'm trying to make Rollup use babel (I'd like to try one new thing at a time) and I followed your suggestion but I'm getting the following errror:

> Error transforming /Users/michael/Projects/expect/modules/index.js with 'babel' plugin: [BABEL] /Users/michael/Projects/expect/modules/x.js: Using removed Babel 5 option: foreign.modules - Use the corresponding module transform plugin in the `plugins` option.

Is that error message telling me that I can't use `presets: [ { modules: false } ]`?

Here's my `rollup.config.js`:

```js
import babel from 'rollup-plugin-babel'
import commonjs from 'rollup-plugin-commonjs'
import nodeResolve from 'rollup-plugin-node-resolve'
import replace from 'rollup-plugin-replace'

const production = process.env.PRODUCTION === 'true';

export default {
  entry: 'modules/index.js',
  dest: 'umd/expect.js',
  moduleName: 'expect',
  format: 'umd',
  plugins: [
    nodeResolve({
      main: true
    }),
    commonjs({
      include: 'node_modules/**',
      namedExports: {
        'define-properties': [ 'supportsDescriptors' ]
      }
    }),
    babel({
      presets: [ 'es2015', { modules: false } ]
    }),
    replace({
      'process.env.NODE_DEBUG': !production
    })
  ]
}
```

If you can provide any insight here I'd greatly appreciate it. Thanks!

**Comment by mjackson** [comment]
@Rich-Harris @robcolburn It looks like [`karma-rollup-plugin`](https://github.com/TrySound/karma-rollup-plugin) could be used to help karma understand how to use rollup for bundling.

**Comment by hzoo** [comment]
@mjackson Ah yea the syntax might be a bit confusing/hard to read but you need another `[]` in there. The options are for each preset so currently
```
 presets: [ 'es2015', { modules: false } ]
```

is wrong because we take a array of strings in "presets" and you are passing in an object for the 2nd argument

```js
{
  "presets": [
    ["es2015", { "modules": false }] // an array of presets but passing in an array as the first argument instead of the string
  ]
}
```

**Comment by mjackson** [comment]
Thanks for the heads up @hzoo, but I still can't get it working properly. The error I'm seeing now is

> Error transforming /Users/michael/Projects/expect/modules/index.js with 'babel' plugin: [BABEL] /Users/michael/Projects/expect/modules/x.js: Invalid options type for foreign

I pushed a [rollup branch](https://github.com/mjackson/expect/tree/rollup) that builds on @Rich-Harris' work. I'm getting the error when trying to run the build (i.e. `npm run build`). Would you mind taking a look?

**Comment by hzoo** [comment]
Might be because you are using an older version of babel in the package.json since the preset options are a newer feature from 6.13.2. Can you try to `rm -rf node_modules/npm i` again

**Comment by ljharb** [comment]
This package is no longer being updated; v21+ is maintained [here](https://github.com/facebook/jest)

**Pull request closed without merging**
