### PR TITLE
Use prepublish script instead of postinstall

### PR DESCRIPTION
**Pull request by rstacruz**
[From npm docs](https://docs.npmjs.com/misc/scripts):

> Don't use install. Use a .gyp file for compilation, and prepublish for anything else. You should almost never have to explicitly set a preinstall or install script. If you are doing this, please consider if there is another option. The only valid use of install or preinstall scripts is for compilation which must be done on the target architecture.

It doesn't explicitly say 'postinstall', but it does recommend compilation by either `.gyp` or `prepublish`. The current postinstall compile script is something that should be done on prepublish instead.

See: #39

### CODE REVIEW

**Comment by rstacruz** [comment]
oh, btw it isn't obvious, but `prepublish` is also invoked when you run `npm install` from within the project's root :)

**Comment by mjackson** [comment]
> it isn't obvious, but prepublish is also invoked when you run npm install from within the project's root

That's exactly why I refuse to use `prepublish`. It doesn't do what it says it does. :)

The `postinstall` hook is only for people who are installing expect straight from the git repo. In that situation, [they won't have a `lib` directory](https://github.com/mjackson/expect/blob/master/npm-scripts/postinstall.js#L8) with the generated code. So we generate it for them so they can immediately use expect locally in the node console.

People who install expect using npm will already have the `lib` directory because [we run the build immediately before](https://github.com/mjackson/expect/blob/6851de3054c5c2ed197ee93d43ade8d6d583aa60/scripts/release.sh#L42) publishing to npm.

**Comment by rstacruz** [comment]
> The postinstall hook is only for people who are installing expect straight from the git repo. 

This is actually not true exactly... I'm using a project with `expect` as a dependency and it still runs.

(I suppose since the postinstall script checks for `lib/`'s existence then it doesn't really do anything, making the statement still kinda true)

```
onmount → npm install

> expect@1.12.2 postinstall /Users/rsc/Projects/rstacruz/onmount/node_modules/expect
> node ./npm-scripts/postinstall.js
```

**Comment by mjackson** [comment]
What I meant was it's only useful for people installing straight from the repo. It's a no-op if you're installing from npm.

**Pull request closed without merging**
