### PR TITLE
Readme: update importing instructions

### PR DESCRIPTION
**Pull request by rstacruz**
`expect = require('expect')` doesn't work anymore. See #72.

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks for the contribution! However, the proper fix is to not use ES6 `export` in the entry point - it wouldn't be acceptable to force users to deal with babel's choice of ES6/CJS interop.

**Comment by rstacruz** [comment]
completely agree. Just put this out there in case @mjackson is adamant to want to use `export default expect` :)

**Comment by ljharb** [comment]
no worries :-) if that's the case then my fix can be reverted and we can find and add a babel transform plugin (https://www.npmjs.com/package/babel-plugin-add-module-exports won't work because there's named exports also :-/)

**Comment by mjackson** [comment]
Thanks for the suggestion, @rstacruz. I'm not adamant about wanting `export default`. I just didn't realize that using extra named exports in that file would change anything about the default export. What's odd to me is that people can still `import { assert } from 'expect'`, for example, even without the named exports. Guess I still have some stuff to learn about ES6 modules and interop with Babel.

**Pull request closed without merging**
